### ISSUE TITLE
News Archive Feeds look at metadata

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#488]
Can we setup the news archive feeds to use metadata? Right now they're not :)

I will respond to job 14653 when this is done.

**Comment by c-schwarze** [comment]
@c-varberg I am passing this one off to you. Should be an easy fix, just call the same functions as the news articles to match metadata. 

Let me know if you have any questions.

**Comment by c-varberg** [comment]
@annmarieven It should be working now. Let me know if you have any problems with it!

**Comment by annmarieven** [comment]
This still isn't working for me.

Live page: https://www.bethel.edu/president/announcements/

News feed block: https://cms.bethel.edu/entity/open.act?id=0af749f18c5865130265fd8051bbf6f3&type=block&

**Comment by c-schwarze** [comment]
News feeds weren't checking the "unique-news" metadata values. Should be working now.

**Comment by annmarieven** [comment]
Appears to be working!
