### ISSUE TITLE
Narrow Images in Firefox

### ISSUE THREAD

**Issue by a-gundy** [betheluniversity/cascade#495]
The site images often appear very narrow in Firefox. Part of the image looks cut off.

![2015-05-06_11-19-52](https://cloud.githubusercontent.com/assets/9537391/7520044/817affde-f4a9-11e4-97f3-900c1a42b022.png)

**Comment by johjacb** [comment]
We fixed some other stuff and it may have taken care of the issue. I was seeing it previously in FF as well, but it looks to me like it is working as expect now.

Check it out and close the issue if its fixed.

**Comment by a-gundy** [comment]
I'm still seeing this. Sometimes a shift+refresh fixes it, but not always. https://www.bethel.edu/graduate/academics/counseling-psychology/

**Comment by e-jameson** [comment]
Looks like this is fixed?

**Comment by johjacb** [comment]
Is this still an issue? Looking good for me in FF 38

**Comment by annmarieven** [comment]
I did some navigating. Looks fixed to me!
