### ISSUE TITLE
Events page broken link

### ISSUE THREAD

**Issue by ale73233** [betheluniversity/cascade#497]
Hi Caleb,
Could you look into this for Brooke Jameson?

events/2015/academic-dates/commencement-spring-cas has the 'Event page link' field filled in but is not actually redirecting there from the calendar, along with the rest of the commencement events I have set to re-direct. I know when I first set up the pages it was working so I'm guessing all the other events with a redirect also don't work now.

Thanks!

**Comment by c-schwarze** [comment]
Fixed. This should be left open until Brooke confirms this working. Can you contact Brooke @ale73233 or @annmarieven ?

**Comment by annmarieven** [comment]
@c-schwarze I just republished a page that is using the external link field but it's still not redirecting for me.

https://cms.bethel.edu/entity/open.act?id=1c0471d58c586513742d45fd5140447d&type=page

live page: https://www.bethel.edu/events/2015/academic-dates/commencement-spring-cas

**Comment by c-schwarze** [comment]
@e-jameson and I talked. We are going to have every event created through Tinker that has an external link, create a redirect in Tinker as well.

**Comment by annmarieven** [comment]
:+1: sounds good! let me know when it's done and I will update Brooke.

**Comment by c-schwarze** [comment]
Having a meeting with Brooke to figure this out.

**Comment by annmarieven** [comment]
setup event approver group to view all meetings, conferences, and rentals events when logged into Tinker
add external link field to Tinker but only make available to event approver group
update so 2 people can be listed as authors
auto redirect based on url entered in Tinker

**Comment by annmarieven** [comment]
@c-schwarze let me know if you need anything else from me :)

**Comment by annmarieven** [comment]
@c-schwarze any update on this?

**Comment by c-schwarze** [comment]
Nearly finished. By early next week, this will be done.

**Comment by c-schwarze** [comment]
Updated

1) Events can have multiple authors (separated my commas)
2) The Event Approver group/role will see all events that are tagged as "rentals/meetings/conferences"
3) Only the Event Approver can see the "External Link" field.
4) Whenever an event is submitted that has a "External Link" field, either
      a) a new redirect is created in tinker
      b) the redirect is updated to the new path, if the path changes.

**Comment by annmarieven** [comment]
Followed up with Brooke in FP job.
