### ISSUE TITLE
Left Hand Nav PHP

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#716]
#Marcel Media has found that our left hand navigation has some php at the end of the urls causing them to redirect. This only happens on individual pages within the left hand nav but not folders.

Can we find a way to get rid of the php in our left hand navigation so that we don't have so many redirects on our site?

We said we could maybe ask Hannon Hill about it or somehow use a publish trigger to strip the php.

Thanks Caleb!

**Comment by c-schwarze** [comment]
I updated our site nav so .php does not appear in the link.

In order for the changes to take effect on all of our pages, we will need to do a site-wide publish. Can I do that tonight or Saturday night? @annmarieven

**Comment by annmarieven** [comment]
I think we can only do a site wide publish during the week. That way if anything major goes wrong, we are around to fix it.

I'll bring it up in slack to see if people have any objections.

**Comment by e-jameson** [comment]
@c-schwarze, it looks like this is stripping too aggressively for directories in the left nav. For example, on https://www.bethel.edu/about/ the Faith URL is linking to https://www.bethel.edu/about/faith instead of https://www.bethel.edu/about/faith/

**Comment by c-schwarze** [comment]
This should be fixed. The issue was actually in our code for the navigation (folders did not have the / at the end).

A site-wide publish is needed to fix this everywhere.

**Comment by annmarieven** [comment]
when you're in staging and click on a page in the left hand nav that is just a page, it jumps you to www instead of keeping you in staging.

is this because of the recent change?
https://staging.bethel.edu/undergrad/financial-aid/ click on dates & deadlines or contact us

**Comment by c-schwarze** [comment]
This should be fixed with the last site publish. Let me know if you see it somewhere.

**Comment by annmarieven** [comment]
still seeing it here: 
https://staging.bethel.edu/undergrad/financial-aid/ click on dates & deadlines or contact us

**Comment by e-jameson** [comment]
Looks like this is fixed. Can we close @c-schwarze ?
